---
- name: Testar Conexao via API no FortiSwitch
  hosts: all
  gather_facts: false

  tasks:
    - name: Coletar status do sistema
      fortinet.fortios.fortios_monitor_fact:
        vdom: "root"
        selector: "system_status"
      register: status_result

    - name: Exibir resultado no console do AWX
      ansible.builtin.debug:
        var: status_result
