---
- name: Testar Conexao com FortiSwitch
  hosts: all
  gather_facts: false

  tasks:
    - name: Coletar status do FortiSwitch
      fortinet.fortios.fortios_fact:
        access_token: ""
        vdom: "root"
        selector: "system_status"
